export enum GamePhase {
  LOBBY = "LOBBY",
  ROLE_ASSIGNMENT = "ROLE_ASSIGNMENT",
  NOMINATION = "NOMINATION",
  VOTING = "VOTING",
  LEGISLATIVE_PRESIDENT = "LEGISLATIVE_PRESIDENT",
  LEGISLATIVE_CHANCELLOR = "LEGISLATIVE_CHANCELLOR",
  POWER = "POWER",
  GAME_OVER = "GAME_OVER",
}
